@startuml uc-tongquan
title uc Tổng quan
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Bệnh nhân" as Patient
actor "Bác sĩ" as Doctor
actor "Quản trị viên\nTổ chức" as OrgAdmin
actor "Bộ Y tế" as Ministry

rectangle "Hệ thống Hồ sơ Y tế điện tử" {
    usecase "Quản lý tài khoản" as UC_Account
    usecase "Quản lý thông tin\ncá nhân" as UC_Profile

    usecase "Quản lý hồ sơ\ny tế" as UC_Records
    usecase "Quản lý quyền\ntruy cập" as UC_Consent
    usecase "Phản hồi yêu cầu\ntruy cập" as UC_Response
    usecase "Quản lý người thân\ntin cậy" as UC_TC

    usecase "Xin xác minh\nchuyên môn" as UC_DoctorVerify
    usecase "Yêu cầu + truy cập\nhồ sơ bệnh nhân" as UC_DoctorAccess
    usecase "Uỷ quyền lại +\ntra cứu khẩn cấp" as UC_DoctorDelegate

    usecase "Quản lý thành viên\nbác sĩ" as UC_OrgMembers
    usecase "Xác minh\nbác sĩ" as UC_OrgVerify

    usecase "Quản lý tổ chức\ny tế" as UC_MinistryOrg
    usecase "Xác minh bác sĩ\nđộc lập" as UC_MinistryDoctor
}

Patient --> UC_Account
Patient --> UC_Profile
Patient --> UC_Records
Patient --> UC_Consent
Patient --> UC_Response
Patient --> UC_TC

Doctor --> UC_Account
Doctor --> UC_Profile
Doctor --> UC_DoctorVerify
Doctor --> UC_DoctorAccess
Doctor --> UC_DoctorDelegate

OrgAdmin --> UC_Account
OrgAdmin --> UC_Profile
OrgAdmin --> UC_OrgMembers
OrgAdmin --> UC_OrgVerify

Ministry --> UC_Account
Ministry --> UC_MinistryOrg
Ministry --> UC_MinistryDoctor

@enduml
