@startuml uc-benh-nhan
title uc Phân rã Bệnh nhân
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Bệnh nhân" as Patient

usecase "Tạo hồ sơ\ny tế" as UC_Create
usecase "Tạo phiên bản\ncập nhật" as UC_Update

usecase "Cấp quyền\ntruy cập" as UC_Grant
usecase "Thu hồi quyền\ntruy cập" as UC_Revoke

usecase "Uỷ quyền\nbác sĩ" as UC_Delegate
usecase "Thu hồi\nuỷ quyền" as UC_RevokeDelegate

usecase "Phê duyệt\nyêu cầu" as UC_Approve
usecase "Từ chối\nyêu cầu" as UC_Reject

usecase "Đăng ký\nCCCD khẩn cấp" as UC_Cccd
usecase "Thêm người\nthân tin cậy" as UC_AddTC
usecase "Thu hồi người\nthân tin cậy" as UC_RemoveTC

Patient --> UC_Create
Patient --> UC_Grant
Patient --> UC_Revoke
Patient --> UC_Delegate
Patient --> UC_RevokeDelegate
Patient --> UC_Approve
Patient --> UC_Cccd
Patient --> UC_AddTC
Patient --> UC_RemoveTC

UC_Update .> UC_Create  : <<extend>>
UC_Reject .> UC_Approve : <<extend>>

@enduml
