@startuml uc-to-chuc
title uc Phân rã Quản trị viên Tổ chức
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Quản trị viên\nTổ chức" as OrgAdmin

usecase "Thêm thành viên\nbác sĩ" as UC_AddMember
usecase "Loại bỏ thành viên\nbác sĩ" as UC_RemoveMember

usecase "Xác minh\nbác sĩ" as UC_Verify
usecase "Thu hồi\nxác minh bác sĩ" as UC_RevokeVerify

OrgAdmin --> UC_AddMember
OrgAdmin --> UC_RemoveMember
OrgAdmin --> UC_Verify
OrgAdmin --> UC_RevokeVerify

UC_RemoveMember .> UC_AddMember : <<extend>>
UC_RevokeVerify .> UC_Verify    : <<extend>>

@enduml
