// Standardized API error codes.
// Mobile maps on error.code, not error.message — keep codes stable.

export const ErrorCodes = Object.freeze({
    // Auth / Role
    ONCHAIN_ROLE_FORBIDDEN: 'ONCHAIN_ROLE_FORBIDDEN',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_SIGNATURE_INVALID: 'AUTH_SIGNATURE_INVALID',

    // Record
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    RECORD_DUPLICATE: 'RECORD_DUPLICATE',
    UPLOAD_TX_FAILED: 'UPLOAD_TX_FAILED',
    UPLOAD_IPFS_FAILED: 'UPLOAD_IPFS_FAILED',

    // Request
    REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
    REQUEST_ALREADY_PROCESSED: 'REQUEST_ALREADY_PROCESSED',
    REQUEST_EXPIRED: 'REQUEST_EXPIRED',

    // Key Share
    KEY_SHARE_NOT_FOUND: 'KEY_SHARE_NOT_FOUND',
    KEY_SHARE_ALREADY_CLAIMED: 'KEY_SHARE_ALREADY_CLAIMED',
    CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',

    // Pending Update
    PENDING_UPDATE_NOT_FOUND: 'PENDING_UPDATE_NOT_FOUND',
    PENDING_UPDATE_EXPIRED: 'PENDING_UPDATE_EXPIRED',
    PENDING_UPDATE_ALREADY_PROCESSED: 'PENDING_UPDATE_ALREADY_PROCESSED',

    // Organization
    ORG_FLOW_DEPRECATED: 'ORG_FLOW_DEPRECATED',
    ORG_MISSING_CHAIN_ID: 'ORG_MISSING_CHAIN_ID',
    ORG_NOT_FOUND: 'ORG_NOT_FOUND',

    // Generic
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    RESOURCE_DUPLICATE: 'RESOURCE_DUPLICATE',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    BACKEND_UNREACHABLE: 'BACKEND_UNREACHABLE',
});
